---
# handlers file for role_docker_setup
- name: Restart docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
